# Generated by Django 5.2.8 on 2025-11-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='შექმნის თარიღი'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='განახლების თარიღი'),
        ),
    ]
